version: '3.4'

services:
  distributed-town-api:
    container_name: distributed-town-api
    image: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SERVER_PORT=3005
      - NODE_ENV=production
      - MAGIC_SECRET_KEY=sk_live_B4234DDF6AE0251D
    ports:
      - "3005:3005"
    command: /bin/bash -c 'yarn; yarn start;'
    networks:
      - distributed-town

networks:
  distributed-town: